doc: update readme.md
notaryproject/tuf pull request #45
Opened 2023-07-25 13:28 UTC by yizha1

Resolve #43 

Signed-off-by: Yi Zha <yizha1@microsoft.com>

2023-07-25 14:24 UTC, FeynmanZhou approved these changes
LGTM

2023-07-26 20:55 UTC, iamsamirzon requested changes

2023-07-26 20:55 UTC, iamsamirzon commented on README.md
> +The initial version of notary TUF-based implementation ran as an additional service on a registry, so was not
```suggestion
The notary TUF-based implementation ran as an additional service on a registry, so was not
```

Removing the phrase "initial version" will help clarify that there isn't any newer version of notary TUF-based implementation.

2023-08-04 15:17 UTC, toddysm approved these changes

2023-08-17 22:57 UTC, priteshbandi approved these changes
LGTM

2023-08-18 01:13 UTC, merged